### ISSUE TITLE
The build should break if TypeScript and/or tslint fails

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/justfix-website#31]
Right now there are a bunch of red marks in my IDE because of `tslint` errors, so I've forcibly squelched tslint-related errors.  But we should either get rid of tslint or make sure that there are no tslint errors as part of our CI pipeline.

We should also do the same with TypeScript code in general, of course.  It seems like `yarn build` doesn't actually raise errors if we have TS type errors, so right now I am just running `node_modules/.bin/tsc --noEmit` to make sure my changes are OK.

**Comment by sraby** [comment]
All ts-lint errors have been fixed in #52 ! I believe that the way `gatsby develop` Is structured it doesn't break the build to introduce typescript errors but now both code editors and circle-ci should pick them up.
