### ISSUE TITLE
$primary-invert doesn't work because findColorInvert() isn't defined

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/justfix-website#34]
While working on #33 I noticed that the `$primary-invert` color seems to evaluate to the literal string `findColorInvert(#0096D7)` in the CSS output, which browsers don't know what to do with.  I think we need to import bulma's `functions.sass`, which the tenant platform does in its [`_bulma-overrides.scss`](https://github.com/JustFixNYC/tenants2/blob/c71545370d61a008c184bfe825fb06a5a5a0139c/frontend/sass/_bulma-overrides.scss#L1).

**Comment by sraby** [comment]
fixed by #65
