### ISSUE TITLE
Website metadata contains references to "gatsby-starter-contentful-typescript", which shows up to end-users on various browsers

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/justfix-website#86]
Jon discovered this on his Android phone while browsing the site... note the "Add starter to home screen" at the bottom:

> ![image](https://user-images.githubusercontent.com/124687/72850558-61ee3f80-3c77-11ea-917e-caa06e6d670b.png)

When he taps on that text, it shows this:

> ![image](https://user-images.githubusercontent.com/124687/72850615-80ecd180-3c77-11ea-8a4c-a10a21beff08.png)

We should probably just do a search for the word "starter" on our codebase and replace anything that needs fixing.

**Comment by sraby** [comment]
Just updated the name in the manifest, as well as in package.json: https://github.com/JustFixNYC/justfix-website/commit/7f150dfc8db7ee0754633a67eacf900de1f2f0ba. That should fix things!
