### ISSUE TITLE
SITE_URL does not seem to be optional

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/justfix-website#96]
Hey, the `.env.sample` file says that `SITE_URL` is optional, but when I tried running the site without setting it, I got a `TypeError: domElem is null` exception.  It was coming from `gatsby-plugin-canonical-urls` so I thought maybe it had something to do with that `SITE_URL`, and when I set it to `https://www.justfix.nyc` everything worked.

**Comment by sraby** [comment]
Fixed in #101
